events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://grafana:3000;
        }

        location /link-config/ {
            proxy_pass http://can_bridge:8080/;
        }
    }
}
